# Generated by Django 6.0.3 on 2026-04-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("pagina_pessoal_url", models.URLField(blank=True, null=True)),
                ("fotografia", models.ImageField(upload_to="docentes/")),
                ("area_especializacao", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("sigla", models.CharField(max_length=10)),
                ("grau", models.CharField(max_length=50)),
                ("duracao_anos", models.IntegerField()),
                ("ects", models.IntegerField()),
                ("descricao", models.TextField()),
                ("saida_profissional", models.TextField()),
            ],
        ),
    ]
