# Generated by Django 6.0.3 on 2026-04-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_projeto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=50)),
                ("descricao", models.TextField()),
                ("logo", models.ImageField(upload_to="tecnologias/")),
                ("website_oficial", models.URLField(blank=True, null=True)),
                ("nivel_dominio", models.IntegerField()),
                ("nivel_interesse", models.IntegerField()),
                ("destaque", models.BooleanField(default=False)),
                (
                    "projetos",
                    models.ManyToManyField(blank=True, to="portfolio.projeto"),
                ),
            ],
        ),
    ]
