# Generated by Django 6.0.3 on 2026-04-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_tecnologia"),
    ]

    operations = [
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autor", models.CharField(max_length=100)),
                ("ano", models.IntegerField()),
                ("resumo", models.TextField()),
                ("area", models.CharField(max_length=100)),
                ("interesse", models.CharField(max_length=100)),
                ("link", models.URLField(blank=True, null=True)),
                ("orientador", models.CharField(max_length=100)),
                ("tecnologias", models.ManyToManyField(to="portfolio.tecnologia")),
            ],
        ),
    ]
