# Generated by Django 6.0.3 on 2026-04-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_tfc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("nivel", models.CharField(max_length=50)),
                ("tipo", models.CharField(max_length=50)),
                ("evidencia", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "projetos",
                    models.ManyToManyField(blank=True, to="portfolio.projeto"),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
                ),
            ],
        ),
    ]
