# Generated by Django 6.0.3 on 2026-04-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_competencia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("bio", models.TextField()),
                ("foto", models.ImageField(upload_to="perfil/")),
                ("email", models.EmailField(max_length=254)),
                ("github", models.URLField(blank=True, null=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("objetivo_profissional", models.TextField()),
            ],
        ),
    ]
