# Generated by Django 6.0.3 on 2026-04-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_formacao"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tfc",
            old_name="resumo",
            new_name="sumario",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="area",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="autor",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="interesse",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="link",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="orientador",
        ),
        migrations.AddField(
            model_name="tfc",
            name="autores",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tfc",
            name="imagem",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="licenciaturas",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tfc",
            name="orientadores",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tfc",
            name="pdf_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="ano",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="tecnologias",
            field=models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
        ),
    ]
