# Generated by Django 6.0.3 on 2026-04-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_rename_resumo_tfc_sumario_remove_tfc_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="ano_letivo",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
