# Generated by Django 6.0.3 on 2026-04-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_recurso"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidadecurricular",
            name="avaliacao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="objetivos",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="programa",
            field=models.TextField(blank=True, null=True),
        ),
    ]
